"use server";

import { revalidatePath } from "next/cache";
import { z } from "zod";
import { requireRole } from "@/lib/auth/session";
import { createClient } from "@/lib/supabase/server";
import { createAdminClient } from "@/lib/supabase/admin";

export type ManageState={error?:string;success?:string};
const optionalText=z.string().trim().max(2000);

export async function saveAssignment(_:ManageState,formData:FormData):Promise<ManageState>{
  const profile=await requireRole("teacher","admin");const parsed=z.object({id:z.union([z.literal(""),z.uuid()]),title:z.string().trim().min(2,"Geef de opdracht een titel.").max(160),description:optionalText,deadline:z.union([z.literal(""),z.iso.datetime({local:true})]),period:z.string().trim().max(80),published:z.boolean()}).safeParse({...Object.fromEntries(formData),published:formData.get("published")==="on"});if(!parsed.success)return{error:parsed.error.issues[0].message};
  const supabase=await createClient();const payload={title:parsed.data.title,description:parsed.data.description,deadline:parsed.data.deadline?new Date(parsed.data.deadline).toISOString():null,period:parsed.data.period||null,is_published:parsed.data.published};let assignmentId=parsed.data.id;
  if(assignmentId){const{error}=await supabase.from("assignments").update(payload).eq("id",assignmentId);if(error)return{error:"Opdracht wijzigen is niet gelukt."};}else{const{data,error}=await supabase.from("assignments").insert({...payload,created_by:profile.id}).select("id").single();if(error||!data)return{error:"Opdracht aanmaken is niet gelukt."};assignmentId=data.id;}
  const cohortIds=formData.getAll("cohortIds").map(String);const goalIds=formData.getAll("goalIds").map(String);
  if(cohortIds.length){const{error}=await supabase.from("cohort_assignments").upsert(cohortIds.map(cohort_id=>({cohort_id,assignment_id:assignmentId})),{onConflict:"cohort_id,assignment_id"});if(error)return{error:"De opdracht is bewaard, maar kon niet aan alle klassen worden gekoppeld."};}
  if(goalIds.length){const{error}=await supabase.from("assignment_learning_goals").upsert(goalIds.map(learning_goal_id=>({learning_goal_id,assignment_id:assignmentId})),{onConflict:"assignment_id,learning_goal_id"});if(error)return{error:"De opdracht is bewaard, maar niet alle leerdoelen zijn gekoppeld."};}
  revalidatePath("/teacher/opdrachten");return{success:parsed.data.id?"Opdracht bijgewerkt.":"Opdracht aangemaakt."};
}

export async function createCohort(_:ManageState,formData:FormData):Promise<ManageState>{await requireRole("admin");const parsed=z.object({name:z.string().trim().min(2).max(100),schoolYear:z.string().regex(/^20\d{2}-20\d{2}$/, "Gebruik bijvoorbeeld 2026-2027.")}).safeParse(Object.fromEntries(formData));if(!parsed.success)return{error:parsed.error.issues[0].message};const supabase=await createClient();const{error}=await supabase.from("cohorts").insert({name:parsed.data.name,school_year:parsed.data.schoolYear});if(error)return{error:"Klas aanmaken is niet gelukt. Mogelijk bestaat deze al."};revalidatePath("/admin");return{success:"Klas aangemaakt."};}

export async function linkCohortMember(_:ManageState,formData:FormData):Promise<ManageState>{await requireRole("admin");const parsed=z.object({profileId:z.uuid(),cohortId:z.uuid(),kind:z.enum(["student","teacher"])}).safeParse(Object.fromEntries(formData));if(!parsed.success)return{error:"Kies een gebruiker en klas."};const supabase=await createClient();let error;if(parsed.data.kind==="student"){({error}=await supabase.from("cohort_members").upsert({student_id:parsed.data.profileId,cohort_id:parsed.data.cohortId},{onConflict:"cohort_id,student_id"}));}else{({error}=await supabase.from("teacher_cohorts").upsert({teacher_id:parsed.data.profileId,cohort_id:parsed.data.cohortId},{onConflict:"teacher_id,cohort_id"}));}if(error)return{error:"Koppelen is niet gelukt."};revalidatePath("/admin");return{success:"Gebruiker aan de klas gekoppeld."};}

export async function saveLearningGoal(_:ManageState,formData:FormData):Promise<ManageState>{await requireRole("admin");const parsed=z.object({id:z.union([z.literal(""),z.uuid()]),title:z.string().trim().min(2).max(240),description:optionalText,domain:z.string().trim().max(100),kerntaak:z.string().trim().max(100),werkproces:z.string().trim().max(100),level:z.string().trim().max(100),sortOrder:z.coerce.number().int().min(0).max(999)}).safeParse(Object.fromEntries(formData));if(!parsed.success)return{error:parsed.error.issues[0].message};const supabase=await createClient();const payload={title:parsed.data.title,description:parsed.data.description,domain:parsed.data.domain||null,kerntaak:parsed.data.kerntaak||null,werkproces:parsed.data.werkproces||null,level:parsed.data.level||null,sort_order:parsed.data.sortOrder};const result=parsed.data.id?await supabase.from("learning_goals").update(payload).eq("id",parsed.data.id):await supabase.from("learning_goals").insert(payload);if(result.error)return{error:"Leerdoel opslaan is niet gelukt."};revalidatePath("/admin/leerdoelen");return{success:parsed.data.id?"Leerdoel bijgewerkt.":"Leerdoel aangemaakt."};}

export async function updateUserRole(_:ManageState,formData:FormData):Promise<ManageState>{const admin=await requireRole("admin");const parsed=z.object({profileId:z.uuid(),role:z.enum(["student","teacher"])}).safeParse(Object.fromEntries(formData));if(!parsed.success)return{error:"Kies een geldige rol."};if(parsed.data.profileId===admin.id)return{error:"Je kunt je eigen beheerdersrol hier niet wijzigen."};const supabase=await createClient();const{error}=await supabase.from("profiles").update({role:parsed.data.role}).eq("id",parsed.data.profileId);if(error)return{error:"De rol kon niet worden gewijzigd."};revalidatePath("/admin");return{success:"Gebruikersrol bijgewerkt."};}

export async function inviteUser(_:ManageState,formData:FormData):Promise<ManageState>{await requireRole("admin");const parsed=z.object({fullName:z.string().trim().min(2).max(120),email:z.email("Vul een geldig e-mailadres in."),role:z.enum(["student","teacher"]),cohortId:z.union([z.literal(""),z.uuid()])}).safeParse(Object.fromEntries(formData));if(!parsed.success)return{error:parsed.error.issues[0].message};const adminClient=createAdminClient();if(!adminClient)return{error:"Uitnodigen is nog niet geactiveerd. Dit wordt aangezet wanneer de centrale database wordt gekoppeld."};const{data,error}=await adminClient.auth.admin.inviteUserByEmail(parsed.data.email,{data:{full_name:parsed.data.fullName}});if(error||!data.user)return{error:"De uitnodiging kon niet worden verstuurd. Mogelijk bestaat dit e-mailadres al."};await adminClient.from("profiles").update({full_name:parsed.data.fullName,role:parsed.data.role}).eq("id",data.user.id);if(parsed.data.cohortId){if(parsed.data.role==="student"){await adminClient.from("cohort_members").insert({student_id:data.user.id,cohort_id:parsed.data.cohortId});}else{await adminClient.from("teacher_cohorts").insert({teacher_id:data.user.id,cohort_id:parsed.data.cohortId});}}revalidatePath("/admin/gebruikers");return{success:`Uitnodiging verstuurd naar ${parsed.data.email}.`};}
