"use server";

import { revalidatePath } from "next/cache";
import { z } from "zod";
import { requireRole } from "@/lib/auth/session";
import { createClient } from "@/lib/supabase/server";
import { createAdminClient } from "@/lib/supabase/admin";

export type ManageState={error?:string;success?:string};
const optionalText=z.string().trim().max(2000);

export async function setAssignmentArchived(_:ManageState,formData:FormData):Promise<ManageState>{const profile=await requireRole("teacher","admin");const parsed=z.object({id:z.uuid(),archived:z.enum(["true","false"])}).safeParse(Object.fromEntries(formData));if(!parsed.success)return{error:"Deze opdracht kon niet worden gevonden."};const supabase=await createClient();const query=supabase.from("assignments").update({archived_at:parsed.data.archived==="true"?new Date().toISOString():null,...(parsed.data.archived==="true"?{is_published:false}:{})}).eq("id",parsed.data.id);if(profile.role==="teacher")query.eq("created_by",profile.id);const{error}=await query;if(error)return{error:"Archiveren is niet gelukt."};revalidatePath("/teacher/opdrachten");revalidatePath("/teacher");revalidatePath("/student");return{success:parsed.data.archived==="true"?"Opdracht gearchiveerd.":"Opdracht hersteld als concept."};}

export async function setLearningGoalArchived(_:ManageState,formData:FormData):Promise<ManageState>{await requireRole("admin");const parsed=z.object({id:z.uuid(),archived:z.enum(["true","false"])}).safeParse(Object.fromEntries(formData));if(!parsed.success)return{error:"Dit leerdoel kon niet worden gevonden."};const supabase=await createClient();const{error}=await supabase.from("learning_goals").update({archived_at:parsed.data.archived==="true"?new Date().toISOString():null}).eq("id",parsed.data.id);if(error)return{error:"Archiveren is niet gelukt."};revalidatePath("/admin/leerdoelen");revalidatePath("/teacher/opdrachten");revalidatePath("/student/leerdoelen");return{success:parsed.data.archived==="true"?"Leerdoel gearchiveerd.":"Leerdoel hersteld."};}

export async function setCohortArchived(_:ManageState,formData:FormData):Promise<ManageState>{await requireRole("admin");const parsed=z.object({id:z.uuid(),archived:z.enum(["true","false"])}).safeParse(Object.fromEntries(formData));if(!parsed.success)return{error:"Deze klas kon niet worden gevonden."};const supabase=await createClient();const{error}=await supabase.from("cohorts").update({archived_at:parsed.data.archived==="true"?new Date().toISOString():null}).eq("id",parsed.data.id);if(error)return{error:"Archiveren is niet gelukt."};revalidatePath("/admin");revalidatePath("/admin/gebruikers");revalidatePath("/teacher");return{success:parsed.data.archived==="true"?"Klas gearchiveerd. Gegevens blijven bewaard.":"Klas hersteld."};}

export async function replaceUserCohort(_:ManageState,formData:FormData):Promise<ManageState>{await requireRole("admin");const parsed=z.object({profileId:z.uuid(),cohortId:z.union([z.literal(""),z.uuid()]),role:z.enum(["student","teacher"])}).safeParse(Object.fromEntries(formData));if(!parsed.success)return{error:"Kies een geldige gebruiker en klas."};const supabase=await createClient();const table=parsed.data.role==="student"?"cohort_members":"teacher_cohorts";const key=parsed.data.role==="student"?"student_id":"teacher_id";const{error:deleteError}=await supabase.from(table).delete().eq(key,parsed.data.profileId);if(deleteError)return{error:"De huidige klaskoppeling kon niet worden gewijzigd."};if(parsed.data.cohortId){const{error}=await supabase.from(table).insert({[key]:parsed.data.profileId,cohort_id:parsed.data.cohortId});if(error)return{error:"De nieuwe klas kon niet worden gekoppeld."};}revalidatePath("/admin");revalidatePath("/admin/gebruikers");return{success:parsed.data.cohortId?"Klaskoppeling bijgewerkt.":"Gebruiker is uit de klas gehaald."};}

export async function setUserActive(_:ManageState,formData:FormData):Promise<ManageState>{const admin=await requireRole("admin");const parsed=z.object({profileId:z.uuid(),active:z.enum(["true","false"])}).safeParse(Object.fromEntries(formData));if(!parsed.success)return{error:"Deze gebruiker kon niet worden gevonden."};if(parsed.data.profileId===admin.id)return{error:"Je kunt je eigen beheerdersaccount niet deactiveren."};const adminClient=createAdminClient();if(!adminClient)return{error:"Accountbeheer is niet beschikbaar."};const active=parsed.data.active==="true";const{error:authError}=await adminClient.auth.admin.updateUserById(parsed.data.profileId,{ban_duration:active?"none":"876000h"});if(authError)return{error:"De toegang kon niet worden aangepast."};const supabase=await createClient();const{error}=await supabase.from("profiles").update({is_active:active}).eq("id",parsed.data.profileId);if(error)return{error:"De toegang is aangepast, maar het profiel kon niet worden bijgewerkt."};revalidatePath("/admin");revalidatePath("/admin/gebruikers");return{success:active?"Gebruiker is weer actief.":"Gebruiker is gedeactiveerd."};}

export async function resendUserInvite(_:ManageState,formData:FormData):Promise<ManageState>{await requireRole("admin");const parsed=z.object({profileId:z.uuid()}).safeParse(Object.fromEntries(formData));if(!parsed.success)return{error:"Deze gebruiker kon niet worden gevonden."};const adminClient=createAdminClient();if(!adminClient)return{error:"Uitnodigingen zijn niet beschikbaar."};const{data,error:getError}=await adminClient.auth.admin.getUserById(parsed.data.profileId);if(getError||!data.user?.email)return{error:"Het e-mailadres kon niet worden gevonden."};if(data.user.email_confirmed_at)return{error:"Dit account is al geactiveerd en kan gewoon inloggen."};const{error}=await adminClient.auth.resend({type:"signup",email:data.user.email});if(error)return{error:"De uitnodiging kon niet opnieuw worden verstuurd."};return{success:`Uitnodiging opnieuw verstuurd naar ${data.user.email}.`};}

export async function saveAssignment(_:ManageState,formData:FormData):Promise<ManageState>{
  const profile=await requireRole("teacher","admin");const parsed=z.object({id:z.union([z.literal(""),z.uuid()]),title:z.string().trim().min(2,"Geef de opdracht een titel.").max(160),description:optionalText,deadline:z.union([z.literal(""),z.iso.datetime({local:true})]),period:z.string().trim().max(80),published:z.boolean()}).safeParse({...Object.fromEntries(formData),published:formData.get("published")==="on"});if(!parsed.success)return{error:parsed.error.issues[0].message};
  const supabase=await createClient();const payload={title:parsed.data.title,description:parsed.data.description,deadline:parsed.data.deadline?new Date(parsed.data.deadline).toISOString():null,period:parsed.data.period||null,is_published:parsed.data.published};let assignmentId=parsed.data.id;
  if(assignmentId){const{error}=await supabase.from("assignments").update(payload).eq("id",assignmentId);if(error)return{error:"Opdracht wijzigen is niet gelukt."};}else{const{data,error}=await supabase.from("assignments").insert({...payload,created_by:profile.id}).select("id").single();if(error||!data)return{error:"Opdracht aanmaken is niet gelukt."};assignmentId=data.id;}
  const cohortIds=formData.getAll("cohortIds").map(String);const goalIds=formData.getAll("goalIds").map(String);
  const{error:cohortDeleteError}=await supabase.from("cohort_assignments").delete().eq("assignment_id",assignmentId);if(cohortDeleteError)return{error:"De opdracht is bewaard, maar de klassen konden niet worden bijgewerkt."};
  const{error:goalDeleteError}=await supabase.from("assignment_learning_goals").delete().eq("assignment_id",assignmentId);if(goalDeleteError)return{error:"De opdracht is bewaard, maar de leerdoelen konden niet worden bijgewerkt."};
  if(cohortIds.length){const{error}=await supabase.from("cohort_assignments").upsert(cohortIds.map(cohort_id=>({cohort_id,assignment_id:assignmentId})),{onConflict:"cohort_id,assignment_id"});if(error)return{error:"De opdracht is bewaard, maar kon niet aan alle klassen worden gekoppeld."};}
  if(goalIds.length){const{error}=await supabase.from("assignment_learning_goals").upsert(goalIds.map(learning_goal_id=>({learning_goal_id,assignment_id:assignmentId})),{onConflict:"assignment_id,learning_goal_id"});if(error)return{error:"De opdracht is bewaard, maar niet alle leerdoelen zijn gekoppeld."};}
  revalidatePath("/teacher/opdrachten");revalidatePath("/teacher");revalidatePath("/student/opdrachten");revalidatePath("/student/modules");return{success:parsed.data.id?"Opdracht bijgewerkt.":"Opdracht aangemaakt."};
}

export async function createCohort(_:ManageState,formData:FormData):Promise<ManageState>{await requireRole("admin");const parsed=z.object({name:z.string().trim().min(2).max(100),schoolYear:z.string().regex(/^20\d{2}-20\d{2}$/, "Gebruik bijvoorbeeld 2026-2027.")}).safeParse(Object.fromEntries(formData));if(!parsed.success)return{error:parsed.error.issues[0].message};const supabase=await createClient();const{error}=await supabase.from("cohorts").insert({name:parsed.data.name,school_year:parsed.data.schoolYear});if(error)return{error:"Klas aanmaken is niet gelukt. Mogelijk bestaat deze al."};revalidatePath("/admin");return{success:"Klas aangemaakt."};}

export async function linkCohortMember(_:ManageState,formData:FormData):Promise<ManageState>{await requireRole("admin");const parsed=z.object({profileId:z.uuid(),cohortId:z.uuid(),kind:z.enum(["student","teacher"])}).safeParse(Object.fromEntries(formData));if(!parsed.success)return{error:"Kies een gebruiker en klas."};const supabase=await createClient();let error;if(parsed.data.kind==="student"){({error}=await supabase.from("cohort_members").upsert({student_id:parsed.data.profileId,cohort_id:parsed.data.cohortId},{onConflict:"cohort_id,student_id"}));}else{({error}=await supabase.from("teacher_cohorts").upsert({teacher_id:parsed.data.profileId,cohort_id:parsed.data.cohortId},{onConflict:"teacher_id,cohort_id"}));}if(error)return{error:"Koppelen is niet gelukt."};revalidatePath("/admin");return{success:"Gebruiker aan de klas gekoppeld."};}

export async function saveLearningGoal(_:ManageState,formData:FormData):Promise<ManageState>{await requireRole("admin");const parsed=z.object({id:z.union([z.literal(""),z.uuid()]),title:z.string().trim().min(2).max(240),description:optionalText,domain:z.string().trim().max(100),kerntaak:z.string().trim().max(100),werkproces:z.string().trim().max(100),level:z.string().trim().max(100),sortOrder:z.coerce.number().int().min(0).max(999)}).safeParse(Object.fromEntries(formData));if(!parsed.success)return{error:parsed.error.issues[0].message};const supabase=await createClient();const payload={title:parsed.data.title,description:parsed.data.description,domain:parsed.data.domain||null,kerntaak:parsed.data.kerntaak||null,werkproces:parsed.data.werkproces||null,level:parsed.data.level||null,sort_order:parsed.data.sortOrder};const result=parsed.data.id?await supabase.from("learning_goals").update(payload).eq("id",parsed.data.id):await supabase.from("learning_goals").insert(payload);if(result.error)return{error:"Leerdoel opslaan is niet gelukt."};revalidatePath("/admin/leerdoelen");return{success:parsed.data.id?"Leerdoel bijgewerkt.":"Leerdoel aangemaakt."};}

export async function updateUserRole(_:ManageState,formData:FormData):Promise<ManageState>{const admin=await requireRole("admin");const parsed=z.object({profileId:z.uuid(),role:z.enum(["student","teacher"])}).safeParse(Object.fromEntries(formData));if(!parsed.success)return{error:"Kies een geldige rol."};if(parsed.data.profileId===admin.id)return{error:"Je kunt je eigen beheerdersrol hier niet wijzigen."};const supabase=await createClient();if(parsed.data.role==="teacher"){const{data:link}=await supabase.from("cohort_members").select("cohort_id").eq("student_id",parsed.data.profileId).limit(1).maybeSingle();await supabase.from("cohort_members").delete().eq("student_id",parsed.data.profileId);if(link?.cohort_id)await supabase.from("teacher_cohorts").upsert({teacher_id:parsed.data.profileId,cohort_id:link.cohort_id},{onConflict:"cohort_id,teacher_id"});}else{const{data:link}=await supabase.from("teacher_cohorts").select("cohort_id").eq("teacher_id",parsed.data.profileId).limit(1).maybeSingle();await supabase.from("teacher_cohorts").delete().eq("teacher_id",parsed.data.profileId);if(link?.cohort_id)await supabase.from("cohort_members").upsert({student_id:parsed.data.profileId,cohort_id:link.cohort_id},{onConflict:"cohort_id,student_id"});}const{error}=await supabase.from("profiles").update({role:parsed.data.role}).eq("id",parsed.data.profileId);if(error)return{error:"De rol kon niet worden gewijzigd."};revalidatePath("/admin");revalidatePath("/admin/gebruikers");return{success:"Gebruikersrol en klaskoppeling bijgewerkt."};}

export async function inviteUser(_:ManageState,formData:FormData):Promise<ManageState>{await requireRole("admin");const parsed=z.object({fullName:z.string().trim().min(2).max(120),email:z.email("Vul een geldig e-mailadres in."),role:z.enum(["student","teacher"]),cohortId:z.union([z.literal(""),z.uuid()])}).safeParse(Object.fromEntries(formData));if(!parsed.success)return{error:parsed.error.issues[0].message};const adminClient=createAdminClient();if(!adminClient)return{error:"Uitnodigen is nog niet geactiveerd. Dit wordt aangezet wanneer de centrale database wordt gekoppeld."};const{data,error}=await adminClient.auth.admin.inviteUserByEmail(parsed.data.email,{data:{full_name:parsed.data.fullName}});if(error||!data.user)return{error:"De uitnodiging kon niet worden verstuurd. Mogelijk bestaat dit e-mailadres al."};await adminClient.from("profiles").update({full_name:parsed.data.fullName,role:parsed.data.role}).eq("id",data.user.id);if(parsed.data.cohortId){if(parsed.data.role==="student"){await adminClient.from("cohort_members").insert({student_id:data.user.id,cohort_id:parsed.data.cohortId});}else{await adminClient.from("teacher_cohorts").insert({teacher_id:data.user.id,cohort_id:parsed.data.cohortId});}}revalidatePath("/admin/gebruikers");return{success:`Uitnodiging verstuurd naar ${parsed.data.email}.`};}
