import Link from "next/link";
import { CohortArchiveForm, CohortForm, CohortLinkForm } from "@/components/forms/management-forms";
import { PageHeader } from "@/components/layout/page-header";
import { requireRole } from "@/lib/auth/session";
import { createClient } from "@/lib/supabase/server";

export default async function AdminDashboard() {
  await requireRole("admin"); const supabase = await createClient();
  const [{ data: profiles }, { data: cohorts }, { data: members }, { data: teacherLinks }, { count: assignmentCount }, { count: goalCount }] = await Promise.all([
    supabase.from("profiles").select("id,full_name,role,is_active").eq("is_active", true).order("full_name"), supabase.from("cohorts").select("id,name,school_year,archived_at").order("archived_at", { ascending: true, nullsFirst: true }).order("name"), supabase.from("cohort_members").select("cohort_id,student_id"), supabase.from("teacher_cohorts").select("cohort_id,teacher_id"), supabase.from("assignments").select("*", { count: "exact", head: true }).is("archived_at", null), supabase.from("learning_goals").select("*", { count: "exact", head: true }).is("archived_at", null),
  ]);
  const students = (profiles ?? []).filter((profile: any) => profile.role === "student"); const teachers = (profiles ?? []).filter((profile: any) => profile.role === "teacher"); const activeCohorts = (cohorts ?? []).filter((cohort: any) => !cohort.archived_at); const archivedCohorts = (cohorts ?? []).filter((cohort: any) => cohort.archived_at);
  const cohortCard = (cohort: any) => <article className={`card p-4 sm:p-5 ${cohort.archived_at ? "opacity-70" : ""}`} key={cohort.id}><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-black">{cohort.name}</h3><p className="text-sm text-slate-500">{cohort.school_year}</p></div><span className="rounded-full bg-teal-50 px-2 py-1 text-xs font-bold text-teal-900">{(members ?? []).filter((member: any) => member.cohort_id === cohort.id).length} studenten</span></div><p className="my-3 text-sm text-slate-600">{(teacherLinks ?? []).filter((link: any) => link.cohort_id === cohort.id).map((link: any) => teachers.find((teacher: any) => teacher.id === link.teacher_id)?.full_name).filter(Boolean).join(", ") || "Nog geen docent"}</p><CohortArchiveForm id={cohort.id} archived={Boolean(cohort.archived_at)} /></article>;
  return <><PageHeader eyebrow="Beheer" title="Opleiding inrichten" description="Beheer klassen en koppelingen. Oude klassen kun je veilig archiveren." action={<Link href="/admin/gebruikers" className="rounded-xl bg-teal-700 px-4 py-2.5 text-sm font-bold text-white">Gebruikers beheren</Link>} /><section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[[students.length, "studenten"], [teachers.length, "docenten"], [assignmentCount ?? 0, "opdrachten"], [goalCount ?? 0, "leerdoelen"]].map(([number, label]) => <div className="card p-5" key={String(label)}><p className="text-3xl font-black">{number}</p><p className="font-bold text-slate-600">{label}</p></div>)}</section><div className="mt-8 grid gap-6 lg:grid-cols-3"><section className="card p-4 sm:p-5"><h2 className="mb-4 text-xl font-black">Klas aanmaken</h2><CohortForm /></section><section className="card p-4 sm:p-5"><h2 className="mb-4 text-xl font-black">Student koppelen</h2><CohortLinkForm profiles={students} cohorts={activeCohorts} kind="student" /></section><section className="card p-4 sm:p-5"><h2 className="mb-4 text-xl font-black">Docent koppelen</h2><CohortLinkForm profiles={teachers} cohorts={activeCohorts} kind="teacher" /></section></div><section className="mt-8"><h2 className="mb-4 text-xl font-black">Actieve klassen</h2><div className="grid gap-4 md:grid-cols-2">{activeCohorts.map(cohortCard)}</div>{archivedCohorts.length > 0 && <details className="mt-7"><summary className="min-h-11 cursor-pointer font-black">Klassenarchief ({archivedCohorts.length})</summary><div className="mt-3 grid gap-4 md:grid-cols-2">{archivedCohorts.map(cohortCard)}</div></details>}</section></>;
}
