"use client";

import { createContext, useContext, useEffect, useMemo, useState } from "react";

export type DemoModule={id:string;title:string;description:string;period:string;assignments:string[]};
export type DemoMoment={id:string;title:string;date:string;kind:string;cohort:string};
type DemoState={modules:DemoModule[];moments:DemoMoment[];users:{id:string;name:string;role:string}[];studentStatus:Record<string,string>;feedbackResponse:string;submissions:string[];notifications:{id:string;title:string;read:boolean}[]};
const initial:DemoState={modules:[{id:"m1",title:"Omgevingsonderzoek",description:"Van trends naar een heldere analyse.",period:"Periode 1",assignments:["DESTEP-analyse","SWOT-analyse","Doelgroepanalyse"]},{id:"m2",title:"Van analyse naar advies",description:"Onderbouw een advies en maak een passende uiting.",period:"Periode 2",assignments:["Adviesposter","Adviespresentatie"]}],moments:[{id:"f1",title:"Snelle check DESTEP-bronnen",date:"8 juli, 10:00",kind:"Snelle check",cohort:"Marketing 4A"},{id:"f2",title:"Peerfeedback adviesposter",date:"15 juli, 13:30",kind:"Feedback van medestudent",cohort:"Marketing 4A"}],users:[{id:"u1",name:"Lina Bakker",role:"Student"},{id:"u2",name:"Sem de Jong",role:"Student"},{id:"u3",name:"Noor van Dijk",role:"Docent"}],studentStatus:{"Lina Bakker":"Feedback verwerken","Sem de Jong":"Wacht op feedback","Yara Smit":"Niets ingeleverd","Omar Aydin":"Op schema","Fleur Visser":"Feedback verwerken"},feedbackResponse:"",submissions:["DESTEP-analyse – versie 1.pdf"],notifications:[{id:"n1",title:"Nieuwe feedback op DESTEP-analyse",read:false},{id:"n2",title:"Feedbackmoment gepland op 8 juli",read:false}]};
type Ctx={state:DemoState;addModule:(m:Omit<DemoModule,"id">)=>void;addMoment:(m:Omit<DemoMoment,"id">)=>void;addUser:(name:string,role:string)=>void;setStudentStatus:(name:string,status:string)=>void;respond:(text:string)=>void;addSubmission:(name:string)=>void;markRead:(id:string)=>void;reset:()=>void};
const DemoContext=createContext<Ctx|null>(null);
export function DemoStateProvider({children}:{children:React.ReactNode}){const[state,setState]=useState(initial);useEffect(()=>{const saved=localStorage.getItem("groeiwijzer-demo");if(saved){try{const parsed=JSON.parse(saved);queueMicrotask(()=>setState(parsed))}catch{}}},[]);useEffect(()=>{localStorage.setItem("groeiwijzer-demo",JSON.stringify(state))},[state]);const value=useMemo<Ctx>(()=>({state,addModule:m=>setState(s=>({...s,modules:[...s.modules,{...m,id:crypto.randomUUID()}]})),addMoment:m=>setState(s=>({...s,moments:[...s.moments,{...m,id:crypto.randomUUID()}],notifications:[...s.notifications,{id:crypto.randomUUID(),title:`Feedbackmoment gepland: ${m.title}`,read:false}]})),addUser:(name,role)=>setState(s=>({...s,users:[...s.users,{id:crypto.randomUUID(),name,role}]})),setStudentStatus:(name,status)=>setState(s=>({...s,studentStatus:{...s.studentStatus,[name]:status}})),respond:text=>setState(s=>({...s,feedbackResponse:text,notifications:s.notifications.map(n=>n.id==="n1"?{...n,read:true}:n)})),addSubmission:name=>setState(s=>({...s,submissions:[...s.submissions,name]})),markRead:id=>setState(s=>({...s,notifications:s.notifications.map(n=>n.id===id?{...n,read:true}:n)})),reset:()=>setState(initial)}),[state]);return <DemoContext.Provider value={value}>{children}</DemoContext.Provider>}
export function useDemo(){const value=useContext(DemoContext);if(!value)throw new Error("DemoStateProvider ontbreekt");return value}
export function DemoResetButton(){const{reset}=useDemo();return <button onClick={reset} className="rounded-lg px-3 py-2 text-xs font-bold text-slate-600 hover:bg-slate-100">Demo resetten</button>}
