import Link from "next/link";
import { AlertTriangle, CalendarClock, Clock3, MessageSquareText, Users } from "lucide-react";
import { BulkUpdateForm } from "@/components/forms/teacher-forms";
import { SummaryCard } from "@/components/dashboard/summary-card";
import { PageHeader } from "@/components/layout/page-header";
import { EmptyState } from "@/components/ui/empty-state";
import { requireRole } from "@/lib/auth/session";
import { createClient } from "@/lib/supabase/server";
import { assignmentStatusLabels, assignmentStatuses } from "@/types/domain";

const one = (value: any) => Array.isArray(value) ? value[0] : value;

export default async function TeacherDashboard({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  const filters = await searchParams; const teacher = await requireRole("teacher", "admin"); const supabase = await createClient();
  const { data: cohortRows } = teacher.role === "admin" ? await supabase.from("cohorts").select("id,name,school_year,archived_at").is("archived_at", null).order("name") : await supabase.from("teacher_cohorts").select("cohort:cohorts(id,name,school_year,archived_at)").eq("teacher_id", teacher.id);
  const cohorts = (cohortRows ?? []).map((row: any) => row.cohort ? one(row.cohort) : row).filter((cohort: any) => cohort && !cohort.archived_at); const cohortId = filters.cohort || cohorts[0]?.id;
  if (!cohortId) return <><PageHeader title="Voortgang" description="Je bent nog niet aan een actieve klas gekoppeld." /><EmptyState title="Geen klassen" description="Vraag een beheerder om je aan een klas te koppelen." /></>;

  const [{ data: memberRows }, { data: assignmentLinks }, { data: moduleLinks }, { data: goals }, { data: moments }, { data: templates }] = await Promise.all([
    supabase.from("cohort_members").select("student:profiles(id,full_name,is_active)").eq("cohort_id", cohortId),
    supabase.from("cohort_assignments").select("assignment:assignments(id,title,deadline,archived_at)").eq("cohort_id", cohortId),
    supabase.from("cohort_modules").select("module:modules(id,title,archived_at,module_assignments(assignment_id))").eq("cohort_id", cohortId),
    supabase.from("learning_goals").select("id,title").is("archived_at", null).order("sort_order"),
    supabase.from("feedback_moments").select("id,title,scheduled_at,status").eq("cohort_id", cohortId).gte("scheduled_at", new Date().toISOString()).order("scheduled_at").limit(5),
    supabase.from("feedback_templates").select("id,title,feedback_text,feedforward_text").eq("teacher_id", teacher.id).order("title"),
  ]);
  const allStudents = (memberRows ?? []).map((row: any) => one(row.student)).filter((student: any) => student?.is_active); let students = filters.student ? allStudents.filter((student: any) => student.id === filters.student) : allStudents;
  const allAssignments = (assignmentLinks ?? []).map((row: any) => one(row.assignment)).filter((assignment: any) => assignment && !assignment.archived_at); const modules = (moduleLinks ?? []).map((row: any) => one(row.module)).filter((module: any) => module && !module.archived_at); const selectedModule = modules.find((module: any) => module.id === filters.module); const moduleAssignmentIds = new Set((selectedModule?.module_assignments ?? []).map((link: any) => link.assignment_id)); const assignments = filters.module ? allAssignments.filter((assignment: any) => moduleAssignmentIds.has(assignment.id)) : allAssignments;
  const ids = students.map((student: any) => student.id); const [{ data: progress }, { data: feedback }, { data: goalProgress }] = ids.length ? await Promise.all([
    supabase.from("student_assignment_progress").select("student_id,assignment_id,status,assignment:assignments(title,deadline)").in("student_id", ids), supabase.from("feedback").select("student_id,assignment_id,processed_by_student").in("student_id", ids).eq("processed_by_student", false), supabase.from("student_learning_goal_progress").select("student_id,learning_goal_id,level").in("student_id", ids),
  ]) : [{ data: [] }, { data: [] }, { data: [] }];
  if (filters.goal) { const allowed = new Set((goalProgress ?? []).filter((goal: any) => goal.learning_goal_id === filters.goal).map((goal: any) => goal.student_id)); students = students.filter((student: any) => allowed.has(student.id)); }
  const filtered = students.filter((student: any) => { const rows = (progress ?? []).filter((row: any) => row.student_id === student.id && (!filters.module || moduleAssignmentIds.has(row.assignment_id))); if (filters.assignment && !rows.some((row: any) => row.assignment_id === filters.assignment && (!filters.status || row.status === filters.status))) return false; if (filters.status && !filters.assignment && !rows.some((row: any) => row.status === filters.status)) return false; if (filters.deadline === "overdue" && !rows.some((row: any) => { const assignment = one(row.assignment); return assignment?.deadline && new Date(assignment.deadline) < new Date() && row.status !== "completed"; })) return false; const unprocessed = (feedback ?? []).some((item: any) => item.student_id === student.id); const invisible = (goalProgress ?? []).some((goal: any) => goal.student_id === student.id && goal.level === "not_visible"); const nothing = !rows.some((row: any) => !["not_started", "in_progress"].includes(row.status)); if (filters.action === "feedback" && !unprocessed) return false; if (filters.action === "waiting" && !rows.some((row: any) => row.status === "submitted")) return false; if (filters.action === "not_visible" && !invisible) return false; if (filters.action === "nothing" && !nothing) return false; return true; });
  const waiting = (progress ?? []).filter((row: any) => row.status === "submitted").length; const unprocessedStudents = new Set((feedback ?? []).map((item: any) => item.student_id)).size;
  const summaries = filtered.map((student: any) => { const rows = (progress ?? []).filter((row: any) => row.student_id === student.id && (!filters.module || moduleAssignmentIds.has(row.assignment_id))); const signals = { nothing: !rows.some((row: any) => !["not_started", "in_progress"].includes(row.status)), overdue: rows.some((row: any) => { const assignment = one(row.assignment); return assignment?.deadline && new Date(assignment.deadline) < new Date() && row.status !== "completed"; }), waiting: rows.some((row: any) => row.status === "submitted"), todo: (feedback ?? []).some((item: any) => item.student_id === student.id), invisible: (goalProgress ?? []).some((goal: any) => goal.student_id === student.id && goal.level === "not_visible") }; return { student, rows, completed: rows.filter((row: any) => row.status === "completed").length, signals }; });
  const signalBadges = (signals: any) => <div className="flex flex-wrap gap-1.5">{signals.nothing && <span className="rounded-full bg-orange-50 px-2 py-1 text-xs font-bold text-orange-900">Niets ingeleverd</span>}{signals.overdue && <span className="inline-flex items-center gap-1 rounded-full bg-red-50 px-2 py-1 text-xs font-bold text-red-800"><AlertTriangle className="size-3" aria-hidden />Deadline verlopen</span>}{signals.waiting && <span className="rounded-full bg-amber-50 px-2 py-1 text-xs font-bold text-amber-900">Wacht op feedback</span>}{signals.todo && <span className="rounded-full bg-fuchsia-50 px-2 py-1 text-xs font-bold text-fuchsia-900">Nog verwerken</span>}{signals.invisible && <span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-bold">Leerdoel niet zichtbaar</span>}{!Object.values(signals).some(Boolean) && <span className="text-sm text-slate-500">Geen directe signalen</span>}</div>;

  return <><PageHeader eyebrow="Docentoverzicht" title="Wie heeft nu wat nodig?" description="Filter op klas, module of leerdoel en ga direct naar de juiste student." action={<div className="flex flex-wrap gap-2"><Link href="/teacher/modules" className="rounded-xl border border-slate-300 bg-white px-4 py-2.5 text-sm font-bold">Modules</Link><Link href="/teacher/feedbackmomenten" className="rounded-xl bg-teal-700 px-4 py-2.5 text-sm font-bold text-white">Feedback plannen</Link></div>} /><section className="mb-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><SummaryCard icon={Users} value={String(allStudents.length)} label="studenten in beeld" hint="Alleen studenten uit de gekozen klas." /><SummaryCard icon={Clock3} value={String(waiting)} label="wachten op feedback" hint="Deze inzendingen vragen een reactie." /><SummaryCard icon={MessageSquareText} value={String(unprocessedStudents)} label="moeten nog verwerken" hint="De student is nu aan zet." /><SummaryCard icon={CalendarClock} value={String(moments?.length ?? 0)} label="feedbackmomenten gepland" hint={moments?.[0] ? `Eerstvolgende: ${moments[0].title}` : "Plan een eerste moment."} /></section>
    <form aria-label="Voortgang filteren" className="card mb-6 grid gap-3 p-4 sm:grid-cols-2 xl:grid-cols-4" method="get"><label className="text-sm font-bold">Klas<select className="field mt-1" name="cohort" defaultValue={cohortId}>{cohorts.map((cohort: any) => <option key={cohort.id} value={cohort.id}>{cohort.name}</option>)}</select></label><label className="text-sm font-bold">Module<select className="field mt-1" name="module" defaultValue={filters.module || ""}><option value="">Alle modules</option>{modules.map((module: any) => <option key={module.id} value={module.id}>{module.title}</option>)}</select></label><label className="text-sm font-bold">Student<select className="field mt-1" name="student" defaultValue={filters.student || ""}><option value="">Alle studenten</option>{allStudents.map((student: any) => <option key={student.id} value={student.id}>{student.full_name}</option>)}</select></label><label className="text-sm font-bold">Opdracht<select className="field mt-1" name="assignment" defaultValue={filters.assignment || ""}><option value="">Alle opdrachten</option>{assignments.map((assignment: any) => <option key={assignment.id} value={assignment.id}>{assignment.title}</option>)}</select></label><label className="text-sm font-bold">Leerdoel<select className="field mt-1" name="goal" defaultValue={filters.goal || ""}><option value="">Alle leerdoelen</option>{(goals ?? []).map((goal: any) => <option key={goal.id} value={goal.id}>{goal.title}</option>)}</select></label><label className="text-sm font-bold">Opdrachtstatus<select className="field mt-1" name="status" defaultValue={filters.status || ""}><option value="">Alle statussen</option>{assignmentStatuses.map((status) => <option key={status} value={status}>{assignmentStatusLabels[status]}</option>)}</select></label><label className="text-sm font-bold">Deadline<select className="field mt-1" name="deadline" defaultValue={filters.deadline || ""}><option value="">Alle deadlines</option><option value="overdue">Deadline verlopen</option></select></label><label className="text-sm font-bold">Openstaande actie<select className="field mt-1" name="action" defaultValue={filters.action || ""}><option value="">Alle acties</option><option value="nothing">Niets ingeleverd</option><option value="waiting">Wacht op feedback</option><option value="feedback">Feedback verwerken</option><option value="not_visible">Leerdoel niet zichtbaar</option></select></label><div className="flex gap-2 sm:col-span-2 xl:col-span-4"><button className="min-h-11 flex-1 rounded-xl bg-teal-700 px-4 font-bold text-white sm:flex-none">Filters toepassen</button><Link className="grid min-h-11 place-items-center rounded-xl border border-slate-300 px-4 text-sm font-bold" href={`/teacher?cohort=${cohortId}`}>Wissen</Link></div></form>
    <section><h2 className="mb-3 text-xl font-black">Studenten <span className="text-base font-semibold text-slate-500">({filtered.length})</span></h2>{summaries.length ? <><div className="space-y-3 md:hidden">{summaries.map(({ student, rows, completed, signals }) => <article className="card p-4" key={student.id}><div className="flex items-start justify-between gap-3"><div><h3 className="font-black">{student.full_name}</h3><p className="mt-1 text-sm text-slate-600">{completed} van {rows.length} afgerond</p></div><Link className="rounded-xl bg-teal-700 px-3 py-2 text-sm font-bold text-white" href={`/teacher/studenten/${student.id}`}>Open</Link></div><div className="mt-3">{signalBadges(signals)}</div></article>)}</div><div className="hidden overflow-x-auto rounded-2xl border border-slate-200 bg-white md:block"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-50"><tr><th className="p-4">Student</th><th className="p-4">Opdrachten</th><th className="p-4">Signaleringen</th><th className="p-4">Actie</th></tr></thead><tbody className="divide-y divide-slate-200">{summaries.map(({ student, rows, completed, signals }) => <tr key={student.id}><td className="p-4 font-black">{student.full_name}</td><td className="p-4">{completed} van {rows.length} afgerond</td><td className="p-4">{signalBadges(signals)}</td><td className="p-4"><Link className="font-bold text-teal-700 underline" href={`/teacher/studenten/${student.id}`}>Open student</Link></td></tr>)}</tbody></table></div></> : <EmptyState title="Geen studenten gevonden" description="Pas de filters aan." />}</section><section className="mt-8"><BulkUpdateForm students={filtered.map((student: any) => ({ id: student.id, name: student.full_name }))} assignments={assignments} templates={templates ?? []} /></section></>;
}
