import { AssignmentArchiveForm, AssignmentForm } from "@/components/forms/management-forms";
import { PageHeader } from "@/components/layout/page-header";
import { requireRole } from "@/lib/auth/session";
import { createClient } from "@/lib/supabase/server";
import { formatDate } from "@/lib/utils";

export default async function AssignmentManagement() {
  const profile = await requireRole("teacher", "admin"); const supabase = await createClient();
  const [{ data: assignments }, { data: cohortsRaw }, { data: goals }, { data: cohortLinks }, { data: goalLinks }] = await Promise.all([
    supabase.from("assignments").select("id,title,description,deadline,period,is_published,created_by,archived_at").order("archived_at", { ascending: true, nullsFirst: true }).order("created_at", { ascending: false }),
    profile.role === "admin" ? supabase.from("cohorts").select("id,name").is("archived_at", null).order("name") : supabase.from("teacher_cohorts").select("cohort:cohorts(id,name,archived_at)").eq("teacher_id", profile.id),
    supabase.from("learning_goals").select("id,title").is("archived_at", null).order("sort_order"),
    supabase.from("cohort_assignments").select("cohort_id,assignment_id"), supabase.from("assignment_learning_goals").select("assignment_id,learning_goal_id"),
  ]);
  const cohorts = (cohortsRaw ?? []).map((row: any) => row.cohort ? (Array.isArray(row.cohort) ? row.cohort[0] : row.cohort) : row).filter((cohort: any) => cohort && !cohort.archived_at);
  const active = (assignments ?? []).filter((assignment: any) => !assignment.archived_at); const archived = (assignments ?? []).filter((assignment: any) => assignment.archived_at);
  const assignmentCard = (assignment: any) => { const item = { ...assignment, cohortIds: (cohortLinks ?? []).filter((link: any) => link.assignment_id === assignment.id).map((link: any) => link.cohort_id), goalIds: (goalLinks ?? []).filter((link: any) => link.assignment_id === assignment.id).map((link: any) => link.learning_goal_id) }; return <details className={`card p-4 sm:p-5 ${assignment.archived_at ? "opacity-70" : ""}`} key={assignment.id}><summary className="min-h-11 cursor-pointer list-none py-1"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-black">{assignment.title}</h3><p className="mt-1 text-sm text-slate-500">{assignment.period || "Geen periode"} · {formatDate(assignment.deadline)} · {item.goalIds.length} leerdoelen</p></div><span className={`rounded-full px-2 py-1 text-xs font-bold ${assignment.archived_at ? "bg-slate-100 text-slate-700" : assignment.is_published ? "bg-emerald-50 text-emerald-900" : "bg-amber-50 text-amber-900"}`}>{assignment.archived_at ? "Gearchiveerd" : assignment.is_published ? "Zichtbaar" : "Concept"}</span></div></summary><div className="mt-5 space-y-5 border-t border-slate-200 pt-5">{!assignment.archived_at && <AssignmentForm assignment={item} cohorts={cohorts} goals={goals ?? []} />}<div className={!assignment.archived_at ? "border-t border-slate-100 pt-4" : ""}><AssignmentArchiveForm id={assignment.id} archived={Boolean(assignment.archived_at)} /><p className="mt-2 text-xs text-slate-500">Archiveren bewaart voortgang en feedback, maar verbergt de opdracht voor studenten.</p></div></div></details>; };
  return <><PageHeader eyebrow="Opdrachtenbeheer" title="Opdrachten en leerdoelen verbinden" description="Maak opdrachten zichtbaar voor klassen, koppel leerdoelen en archiveer oude onderdelen zonder historie te verliezen." /><div className="grid gap-7 xl:grid-cols-[.8fr_1.2fr]"><section className="card h-fit p-4 sm:p-5"><h2 className="mb-4 text-xl font-black">Nieuwe opdracht</h2><AssignmentForm cohorts={cohorts} goals={goals ?? []} /></section><section><h2 className="mb-4 text-xl font-black">Actieve opdrachten</h2><div className="space-y-4">{active.map(assignmentCard)}</div>{archived.length > 0 && <details className="mt-7"><summary className="min-h-11 cursor-pointer font-black">Archief ({archived.length})</summary><div className="mt-3 space-y-4">{archived.map(assignmentCard)}</div></details>}</section></div></>;
}
