import Link from "next/link";
import { PageHeader } from "@/components/layout/page-header";
import { StatusBadge } from "@/components/status/status-badge";
import { EmptyState } from "@/components/ui/empty-state";
import { requireRole } from "@/lib/auth/session";
import { createClient } from "@/lib/supabase/server";

const one=(v:any)=>Array.isArray(v)?v[0]:v;
export default async function StudentModules(){const profile=await requireRole("student");const supabase=await createClient();const[{data:modules},{data:progress}]=await Promise.all([supabase.from("modules").select("id,title,description,period,module_assignments(sort_order,assignment:assignments(id,title))").eq("is_published",true).order("sort_order"),supabase.from("student_assignment_progress").select("assignment_id,status").eq("student_id",profile.id)]);const statusMap=new Map((progress??[]).map((p:any)=>[p.assignment_id,p.status]));return <><PageHeader eyebrow="Mijn route" title="Modules" description="Werk stap voor stap door samenhangende opdrachten. Per opdracht zie je wat je al hebt gedaan en wat daarna komt."/>{modules?.length?<div className="space-y-5">{modules.map((m:any)=><article className="card p-5 sm:p-6" key={m.id}><p className="text-xs font-bold uppercase tracking-wide text-teal-700">{m.period||"Doorlopend"}</p><h2 className="mt-1 text-xl font-black">{m.title}</h2><p className="mt-2 text-sm text-slate-600">{m.description}</p><ol className="mt-5 space-y-3">{(m.module_assignments??[]).sort((a:any,b:any)=>a.sort_order-b.sort_order).map((link:any,index:number)=>{const a=one(link.assignment);const status=statusMap.get(a?.id) as any;return a?<li className="flex items-center gap-3 rounded-xl bg-slate-50 p-3" key={a.id}><span className="grid size-8 shrink-0 place-items-center rounded-full bg-white font-black text-teal-800">{index+1}</span><Link className="min-w-0 flex-1 font-bold text-slate-900 underline decoration-slate-300" href={`/student/opdrachten/${a.id}`}>{a.title}</Link>{status&&<StatusBadge value={status}/>}</li>:null})}</ol></article>)}</div>:<EmptyState title="Nog geen modules" description="Zodra je docent een module publiceert, verschijnt die hier."/>}</>}
