import { LearningGoalArchiveForm, LearningGoalForm } from "@/components/forms/management-forms";
import { PageHeader } from "@/components/layout/page-header";
import { requireRole } from "@/lib/auth/session";
import { createClient } from "@/lib/supabase/server";

export default async function GoalManagement() {
  await requireRole("admin"); const supabase = await createClient(); const { data: goals } = await supabase.from("learning_goals").select("*").order("archived_at", { ascending: true, nullsFirst: true }).order("domain").order("sort_order");
  const active = (goals ?? []).filter((goal: any) => !goal.archived_at); const archived = (goals ?? []).filter((goal: any) => goal.archived_at);
  const card = (goal: any) => <details className={`card p-4 sm:p-5 ${goal.archived_at ? "opacity-70" : ""}`} key={goal.id}><summary className="min-h-11 cursor-pointer list-none py-1"><p className="text-xs font-bold uppercase tracking-wide text-teal-700">{goal.domain || "Zonder domein"} · {goal.kerntaak || "—"} · {goal.werkproces || "—"}</p><div className="mt-2 flex items-start justify-between gap-3"><h3 className="font-black">{goal.title}</h3>{goal.archived_at && <span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-bold">Gearchiveerd</span>}</div></summary><div className="mt-5 space-y-5 border-t border-slate-200 pt-5">{!goal.archived_at && <LearningGoalForm goal={goal} />}<div className={!goal.archived_at ? "border-t border-slate-100 pt-4" : ""}><LearningGoalArchiveForm id={goal.id} archived={Boolean(goal.archived_at)} /><p className="mt-2 text-xs text-slate-500">Bestaande feedback blijft bewaard.</p></div></div></details>;
  return <><PageHeader eyebrow="Leerdoelenbeheer" title="Leerdoelen ordenen" description="Beheer de bibliotheek en archiveer verouderde doelen zonder eerder werk te verwijderen." /><div className="grid gap-7 xl:grid-cols-[.8fr_1.2fr]"><section className="card h-fit p-4 sm:p-5"><h2 className="mb-4 text-xl font-black">Nieuw leerdoel</h2><LearningGoalForm /></section><section><h2 className="mb-4 text-xl font-black">Actieve leerdoelen</h2><div className="space-y-4">{active.map(card)}</div>{archived.length > 0 && <details className="mt-7"><summary className="min-h-11 cursor-pointer font-black">Archief ({archived.length})</summary><div className="mt-3 space-y-4">{archived.map(card)}</div></details>}</section></div></>;
}
