"use client";

import { useActionState } from "react";
import {
  createCohort,
  inviteUser,
  linkCohortMember,
  replaceUserCohort,
  resendUserInvite,
  saveAssignment,
  saveLearningGoal,
  setAssignmentArchived,
  setCohortArchived,
  setLearningGoalArchived,
  setUserActive,
  updateUserRole,
  type ManageState,
} from "@/app/actions/management";
import { Button } from "@/components/ui/button";

function Message({ state }: { state: ManageState }) {
  if (state.error) return <p className="rounded-xl bg-red-50 p-3 text-sm font-bold text-red-800" role="alert">{state.error}</p>;
  if (state.success) return <p className="rounded-xl bg-emerald-50 p-3 text-sm font-bold text-emerald-900" role="status">{state.success}</p>;
  return null;
}

export function AssignmentForm({ assignment, cohorts, goals }: { assignment?: any; cohorts: any[]; goals: any[] }) {
  const [state, action, pending] = useActionState(saveAssignment, {});
  return <form action={action} className="space-y-4"><input type="hidden" name="id" value={assignment?.id ?? ""} /><label className="block text-sm font-bold">Titel<input className="field mt-1" name="title" defaultValue={assignment?.title} required maxLength={160} /></label><label className="block text-sm font-bold">Beschrijving<textarea className="field mt-1 min-h-24" name="description" defaultValue={assignment?.description} maxLength={2000} /></label><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-bold">Deadline<input className="field mt-1" type="datetime-local" name="deadline" defaultValue={assignment?.deadline?.slice(0, 16)} /></label><label className="text-sm font-bold">Periode<input className="field mt-1" name="period" defaultValue={assignment?.period} maxLength={80} /></label></div><label className="flex min-h-11 items-center gap-2 text-sm font-bold"><input className="size-5 accent-teal-700" type="checkbox" name="published" defaultChecked={assignment?.is_published} />Zichtbaar voor gekoppelde klassen</label><fieldset><legend className="text-sm font-bold">Klassen</legend><div className="mt-2 grid gap-2 sm:grid-cols-2">{cohorts.map((cohort) => <label className="flex min-h-11 items-center gap-2 rounded-lg px-2 text-sm hover:bg-slate-50" key={cohort.id}><input type="checkbox" name="cohortIds" value={cohort.id} className="size-5 accent-teal-700" defaultChecked={assignment?.cohortIds?.includes(cohort.id)} />{cohort.name}</label>)}</div></fieldset><fieldset><legend className="text-sm font-bold">Leerdoelen</legend><div className="mt-2 max-h-56 space-y-1 overflow-y-auto rounded-xl border border-slate-200 p-2">{goals.map((goal) => <label className="flex min-h-11 items-start gap-2 rounded-lg p-2 text-sm hover:bg-slate-50" key={goal.id}><input type="checkbox" name="goalIds" value={goal.id} className="mt-0.5 size-5 shrink-0 accent-teal-700" defaultChecked={assignment?.goalIds?.includes(goal.id)} />{goal.title}</label>)}</div></fieldset><Message state={state} /><Button className="w-full sm:w-auto" disabled={pending}>{pending ? "Opslaan…" : assignment ? "Wijzigingen opslaan" : "Opdracht aanmaken"}</Button></form>;
}

export function CohortForm() { const [state, action, pending] = useActionState(createCohort, {}); return <form action={action} className="space-y-3"><label className="block text-sm font-bold">Naam<input className="field mt-1" name="name" required placeholder="Marketing & Communicatie 4C" /></label><label className="block text-sm font-bold">Schooljaar<input className="field mt-1" name="schoolYear" required defaultValue="2026-2027" /></label><Message state={state} /><Button className="w-full sm:w-auto" disabled={pending}>{pending ? "Aanmaken…" : "Klas aanmaken"}</Button></form>; }

export function CohortLinkForm({ profiles, cohorts, kind }: { profiles: any[]; cohorts: any[]; kind: "student" | "teacher" }) { const [state, action, pending] = useActionState(linkCohortMember, {}); return <form action={action} className="space-y-3"><input type="hidden" name="kind" value={kind} /><label className="block text-sm font-bold">{kind === "student" ? "Student" : "Docent"}<select className="field mt-1" name="profileId" required><option value="">Kies</option>{profiles.map((profile) => <option key={profile.id} value={profile.id}>{profile.full_name}</option>)}</select></label><label className="block text-sm font-bold">Klas<select className="field mt-1" name="cohortId" required><option value="">Kies</option>{cohorts.map((cohort) => <option key={cohort.id} value={cohort.id}>{cohort.name}</option>)}</select></label><Message state={state} /><Button className="w-full sm:w-auto" disabled={pending}>{pending ? "Koppelen…" : "Aan klas koppelen"}</Button></form>; }

export function LearningGoalForm({ goal }: { goal?: any }) { const [state, action, pending] = useActionState(saveLearningGoal, {}); return <form action={action} className="space-y-3"><input type="hidden" name="id" value={goal?.id ?? ""} /><label className="block text-sm font-bold">Leerdoel<textarea className="field mt-1 min-h-20" name="title" defaultValue={goal?.title} required maxLength={240} /></label><label className="block text-sm font-bold">Beschrijving<textarea className="field mt-1 min-h-20" name="description" defaultValue={goal?.description} maxLength={2000} /></label><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-bold">Domein<input className="field mt-1" name="domain" defaultValue={goal?.domain} /></label><label className="text-sm font-bold">Niveau/kader<input className="field mt-1" name="level" defaultValue={goal?.level} /></label><label className="text-sm font-bold">Kerntaak<input className="field mt-1" name="kerntaak" defaultValue={goal?.kerntaak} /></label><label className="text-sm font-bold">Werkproces<input className="field mt-1" name="werkproces" defaultValue={goal?.werkproces} /></label><label className="text-sm font-bold">Volgorde<input className="field mt-1" type="number" min="0" max="999" name="sortOrder" defaultValue={goal?.sort_order ?? 0} /></label></div><Message state={state} /><Button className="w-full sm:w-auto" disabled={pending}>{pending ? "Opslaan…" : goal ? "Wijzigingen opslaan" : "Leerdoel aanmaken"}</Button></form>; }

export function UserRoleForm({ profile }: { profile: { id: string; role: "student" | "teacher" } }) { const [state, action, pending] = useActionState(updateUserRole, {}); return <form action={action} className="flex flex-col gap-2 sm:flex-row sm:items-start"><input type="hidden" name="profileId" value={profile.id} /><label className="sr-only" htmlFor={`role-${profile.id}`}>Gebruikersrol</label><select id={`role-${profile.id}`} className="field min-w-36 flex-1" name="role" defaultValue={profile.role}><option value="student">Student</option><option value="teacher">Docent</option></select><Button disabled={pending}>{pending ? "Opslaan…" : "Rol opslaan"}</Button><Message state={state} /></form>; }

export function InviteUserForm({ cohorts }: { cohorts: { id: string; name: string }[] }) { const [state, action, pending] = useActionState(inviteUser, {}); return <form action={action} className="space-y-4"><label className="block text-sm font-bold">Naam<input className="field mt-1" name="fullName" autoComplete="name" required /></label><label className="block text-sm font-bold">E-mailadres<input className="field mt-1" type="email" name="email" autoComplete="email" required /></label><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-bold">Rol<select className="field mt-1" name="role"><option value="student">Student</option><option value="teacher">Docent</option></select></label><label className="text-sm font-bold">Klas<select className="field mt-1" name="cohortId"><option value="">Later koppelen</option>{cohorts.map((cohort) => <option key={cohort.id} value={cohort.id}>{cohort.name}</option>)}</select></label></div><Message state={state} /><Button className="w-full sm:w-auto" disabled={pending}>{pending ? "Versturen…" : "Uitnodiging versturen"}</Button></form>; }

type ArchiveKind = "assignment" | "goal" | "cohort";
function ArchiveForm({ kind, id, archived }: { kind: ArchiveKind; id: string; archived: boolean }) { const serverAction = kind === "assignment" ? setAssignmentArchived : kind === "goal" ? setLearningGoalArchived : setCohortArchived; const [state, action, pending] = useActionState(serverAction, {}); const label = kind === "assignment" ? "Opdracht" : kind === "goal" ? "Leerdoel" : "Klas"; return <form action={action} className="space-y-2"><input type="hidden" name="id" value={id} /><input type="hidden" name="archived" value={archived ? "false" : "true"} /><Button type="submit" variant="secondary" disabled={pending}>{pending ? "Bezig…" : archived ? `${label} herstellen` : `${label} archiveren`}</Button><Message state={state} /></form>; }
export function AssignmentArchiveForm(props: { id: string; archived: boolean }) { return <ArchiveForm kind="assignment" {...props} />; }
export function LearningGoalArchiveForm(props: { id: string; archived: boolean }) { return <ArchiveForm kind="goal" {...props} />; }
export function CohortArchiveForm(props: { id: string; archived: boolean }) { return <ArchiveForm kind="cohort" {...props} />; }

export function UserManagementForm({ profile, cohorts, currentCohortId }: { profile: { id: string; role: "student" | "teacher"; is_active: boolean }; cohorts: { id: string; name: string }[]; currentCohortId?: string }) {
  const [classState, classAction, classPending] = useActionState(replaceUserCohort, {}); const [activeState, activeAction, activePending] = useActionState(setUserActive, {}); const [inviteState, inviteAction, invitePending] = useActionState(resendUserInvite, {});
  return <div className="space-y-4"><UserRoleForm profile={profile} /><form action={classAction} className="space-y-2"><input type="hidden" name="profileId" value={profile.id} /><input type="hidden" name="role" value={profile.role} /><label className="block text-sm font-bold">Klas<select className="field mt-1" name="cohortId" defaultValue={currentCohortId ?? ""}><option value="">Geen klas</option>{cohorts.map((cohort) => <option value={cohort.id} key={cohort.id}>{cohort.name}</option>)}</select></label><Button className="w-full sm:w-auto" variant="secondary" disabled={classPending}>{classPending ? "Bijwerken…" : "Klaskoppeling opslaan"}</Button><Message state={classState} /></form><div className="flex flex-col gap-2 sm:flex-row"><form action={inviteAction}><input type="hidden" name="profileId" value={profile.id} /><Button className="w-full" variant="secondary" disabled={invitePending}>{invitePending ? "Versturen…" : "Uitnodiging opnieuw sturen"}</Button></form><form action={activeAction}><input type="hidden" name="profileId" value={profile.id} /><input type="hidden" name="active" value={profile.is_active ? "false" : "true"} /><Button className="w-full" variant="secondary" disabled={activePending}>{activePending ? "Bezig…" : profile.is_active ? "Gebruiker deactiveren" : "Gebruiker activeren"}</Button></form></div><Message state={inviteState} /><Message state={activeState} /></div>;
}
