"use client";

import { useActionState } from "react";
import { addEvidence, addReflection, processFeedback, submitAssignmentVersion } from "@/app/actions/student";
import { Button } from "@/components/ui/button";

function Message({ state }: { state: { error?: string; success?: string } }) { if (state.error) return <p role="alert" className="rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-800">{state.error}</p>; if (state.success) return <p role="status" className="rounded-xl bg-emerald-50 p-3 text-sm font-semibold text-emerald-900">{state.success}</p>; return null; }

export function EvidenceForm({ contextType, contextId }: { contextType: "assignment" | "goal"; contextId: string }) { const [state, action, pending] = useActionState(addEvidence, {}); return <form action={action} className="space-y-4"><input type="hidden" name="contextType" value={contextType}/><input type="hidden" name="contextId" value={contextId}/><label className="block text-sm font-bold">Titel<input className="field mt-1" name="title" required maxLength={160}/></label><label className="block text-sm font-bold">Link <span className="font-normal text-slate-500">(optioneel)</span><input className="field mt-1" name="url" type="url" placeholder="https://…"/></label><label className="block text-sm font-bold">Of kies een bestand<input className="field mt-1" name="file" type="file" accept=".pdf,.png,.jpg,.jpeg,.docx,.pptx"/></label><label className="block text-sm font-bold">Korte toelichting <span className="font-normal text-slate-500">(optioneel)</span><textarea className="field mt-1 min-h-24" name="description" maxLength={1000}/></label><Message state={state}/><Button disabled={pending}>{pending ? "Toevoegen…" : "Voeg bewijs toe"}</Button></form>; }

export function ReflectionForm({ contextType, contextId }: { contextType: "assignment" | "goal"; contextId: string }) { const [state, action, pending] = useActionState(addReflection, {}); return <form action={action} className="space-y-4"><input type="hidden" name="contextType" value={contextType}/><input type="hidden" name="contextId" value={contextId}/><label className="block text-sm font-bold">Wat heb je geleerd en wat wordt je volgende stap?<textarea className="field mt-1 min-h-28" name="reflection" required minLength={3} maxLength={2000}/></label><Message state={state}/><Button disabled={pending}>{pending ? "Opslaan…" : "Reflectie opslaan"}</Button></form>; }

export function ProcessFeedbackForm({ feedbackId, path, submissions=[] }: { feedbackId: string; path: string; submissions?: {id:string;version_number:number}[] }) { const [state, action, pending] = useActionState(processFeedback, {}); return <form action={action} className="mt-4 space-y-3 rounded-xl bg-fuchsia-50 p-4"><input type="hidden" name="feedbackId" value={feedbackId}/><input type="hidden" name="path" value={path}/><label className="block text-sm font-bold text-fuchsia-950">Wat heb je met deze feedback gedaan?<textarea className="field mt-1 min-h-24" name="reflection" required minLength={3} maxLength={2000}/></label>{submissions.length?<label className="block text-sm font-bold">Koppel je verbeterde versie<select className="field mt-1" name="submissionId"><option value="">Geen versie koppelen</option>{submissions.map(s=><option key={s.id} value={s.id}>Versie {s.version_number}</option>)}</select></label>:<input type="hidden" name="submissionId" value=""/>}<Message state={state}/><Button disabled={pending} className="bg-fuchsia-800 hover:bg-fuchsia-900">{pending ? "Opslaan…" : "Reactie opslaan en afronden"}</Button></form>; }

export function SubmissionForm({assignmentId}:{assignmentId:string}) { const [state,action,pending]=useActionState(submitAssignmentVersion,{}); return <form action={action} className="space-y-4"><input type="hidden" name="assignmentId" value={assignmentId}/><label className="block text-sm font-bold">Bestand<input className="field mt-1" type="file" name="file" accept=".pdf,.png,.jpg,.jpeg,.docx,.pptx"/></label><label className="block text-sm font-bold">Of een link<input className="field mt-1" type="url" name="url" placeholder="https://…"/></label><label className="block text-sm font-bold">Wat is er nieuw in deze versie?<textarea className="field mt-1 min-h-24" name="note" maxLength={2000}/></label><Message state={state}/><Button disabled={pending}>{pending?"Inleveren…":"Nieuwe versie inleveren"}</Button></form>; }
