"use client";

import { useActionState, useState } from "react";
import { addTeacherFeedback, bulkUpdate, updateAssignmentStatus, updateGoalLevel } from "@/app/actions/teacher";
import { Button } from "@/components/ui/button";
import { assignmentStatusLabels, assignmentStatuses, learningGoalLevelLabels, learningGoalLevels, type AssignmentStatus, type LearningGoalLevel } from "@/types/domain";

type Template={id:string;title:string;feedback_text:string;feedforward_text:string};
function Message({state}:{state:{error?:string;success?:string}}){return state.error?<p role="alert" className="mt-3 rounded-xl bg-red-50 p-3 text-sm font-bold text-red-800">{state.error}</p>:state.success?<p role="status" className="mt-3 rounded-xl bg-emerald-50 p-3 text-sm font-bold text-emerald-900">{state.success}</p>:null}
export function AssignmentStatusForm({studentId,assignmentId,value}:{studentId:string;assignmentId:string;value:AssignmentStatus}){const[state,action,pending]=useActionState(updateAssignmentStatus,{});return <form action={action} className="flex flex-wrap items-center gap-2"><input type="hidden" name="studentId" value={studentId}/><input type="hidden" name="assignmentId" value={assignmentId}/><select aria-label="Opdrachtstatus" className="field min-w-48 flex-1" name="status" defaultValue={value}>{assignmentStatuses.map(s=><option value={s} key={s}>{assignmentStatusLabels[s]}</option>)}</select><Button disabled={pending}>{pending?"Opslaan…":"Opslaan"}</Button><Message state={state}/></form>}
export function GoalLevelForm({studentId,goalId,value}:{studentId:string;goalId:string;value:LearningGoalLevel}){const[state,action,pending]=useActionState(updateGoalLevel,{});return <form action={action} className="flex flex-wrap items-center gap-2"><input type="hidden" name="studentId" value={studentId}/><input type="hidden" name="goalId" value={goalId}/><select aria-label="Leerdoelniveau" className="field min-w-52 flex-1" name="level" defaultValue={value}>{learningGoalLevels.map(s=><option value={s} key={s}>{learningGoalLevelLabels[s]}</option>)}</select><Button disabled={pending}>{pending?"Opslaan…":"Opslaan"}</Button><Message state={state}/></form>}

export function FeedbackForm({studentId,assignments,goals,templates=[]}:{studentId:string;assignments:{id:string;title:string}[];goals:{id:string;title:string}[];templates?:Template[]}){const[state,action,pending]=useActionState(addTeacherFeedback,{});const[feedback,setFeedback]=useState("");const[feedforward,setFeedforward]=useState("");function choose(id:string){const t=templates.find(x=>x.id===id);if(t){setFeedback(t.feedback_text);setFeedforward(t.feedforward_text)}}return <form action={action} className="space-y-4"><input type="hidden" name="studentId" value={studentId}/>{templates.length?<label className="block text-sm font-bold">Begin met een sjabloon<select className="field mt-1" defaultValue="" onChange={e=>choose(e.target.value)}><option value="">Schrijf zelf</option>{templates.map(t=><option value={t.id} key={t.id}>{t.title}</option>)}</select></label>:null}<div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold">Opdracht <span className="font-normal text-slate-500">(optioneel)</span><select className="field mt-1" name="assignmentId"><option value="">Geen opdracht</option>{assignments.map(a=><option key={a.id} value={a.id}>{a.title}</option>)}</select></label><label className="text-sm font-bold">Leerdoel <span className="font-normal text-slate-500">(optioneel)</span><select className="field mt-1" name="goalId"><option value="">Geen leerdoel</option>{goals.map(g=><option key={g.id} value={g.id}>{g.title}</option>)}</select></label></div><label className="block text-sm font-bold">Wat gaat al goed?<textarea className="field mt-1 min-h-28" name="feedbackText" required maxLength={3000} value={feedback} onChange={e=>setFeedback(e.target.value)}/></label><label className="block text-sm font-bold">Wat is de volgende stap?<textarea className="field mt-1 min-h-28" name="feedforwardText" required maxLength={3000} value={feedforward} onChange={e=>setFeedforward(e.target.value)}/></label><Message state={state}/><Button disabled={pending}>{pending?"Opslaan…":"Feedback geven"}</Button></form>}

export function BulkUpdateForm({students,assignments,templates=[]}:{students:{id:string;name:string}[];assignments:{id:string;title:string}[];templates?:Template[]}){const[state,action,pending]=useActionState(bulkUpdate,{});const[feedback,setFeedback]=useState("");const[feedforward,setFeedforward]=useState("");function choose(id:string){const t=templates.find(x=>x.id===id);if(t){setFeedback(t.feedback_text);setFeedforward(t.feedforward_text)}}return <form action={action} className="card p-5"><h2 className="text-lg font-black">Meerdere studenten bijwerken</h2><p className="mt-1 text-sm text-slate-600">Selecteer studenten, kies één opdracht en werk iedereen in één keer bij.</p><fieldset className="mt-4"><legend className="text-sm font-bold">Studenten</legend><div className="mt-2 grid max-h-48 gap-2 overflow-y-auto rounded-xl border border-slate-200 p-3 sm:grid-cols-2">{students.map(s=><label className="flex items-center gap-2 text-sm" key={s.id}><input className="size-4 accent-teal-700" type="checkbox" name="studentIds" value={s.id}/>{s.name}</label>)}</div></fieldset><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold">Opdracht<select className="field mt-1" name="assignmentId" required><option value="">Kies een opdracht</option>{assignments.map(a=><option key={a.id} value={a.id}>{a.title}</option>)}</select></label><label className="text-sm font-bold">Nieuwe status<select className="field mt-1" name="status" defaultValue="feedback_received">{assignmentStatuses.map(s=><option value={s} key={s}>{assignmentStatusLabels[s]}</option>)}</select></label></div><details className="mt-4 rounded-xl bg-slate-50 p-4"><summary className="cursor-pointer font-bold">Dezelfde feedback toevoegen (optioneel)</summary><div className="mt-4 space-y-4">{templates.length?<label className="block text-sm font-bold">Gebruik sjabloon<select className="field mt-1" defaultValue="" onChange={e=>choose(e.target.value)}><option value="">Schrijf zelf</option>{templates.map(t=><option value={t.id} key={t.id}>{t.title}</option>)}</select></label>:null}<div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold">Wat gaat al goed?<textarea name="feedbackText" className="field mt-1 min-h-24" maxLength={1000} value={feedback} onChange={e=>setFeedback(e.target.value)}/></label><label className="text-sm font-bold">Volgende stap<textarea name="feedforwardText" className="field mt-1 min-h-24" maxLength={1000} value={feedforward} onChange={e=>setFeedforward(e.target.value)}/></label></div></div></details><Message state={state}/><Button className="mt-4" disabled={pending}>{pending?"Bijwerken…":"Selectie bijwerken"}</Button></form>}
