"use client";

import { useActionState } from "react";
import { saveFeedbackMoment, saveFeedbackTemplate, saveModule } from "@/app/actions/workflow";
import { Button } from "@/components/ui/button";

type Option = { id: string; title?: string; name?: string };
function Message({ state }: { state: { error?: string; success?: string } }) {
  if (state.error) return <p role="alert" className="rounded-xl bg-red-50 p-3 text-sm font-bold text-red-800">{state.error}</p>;
  if (state.success) return <p role="status" className="rounded-xl bg-emerald-50 p-3 text-sm font-bold text-emerald-900">{state.success}</p>;
  return null;
}

export function ModuleForm({ module, cohorts, assignments }: { module?: any; cohorts: Option[]; assignments: Option[] }) {
  const [state, action, pending] = useActionState(saveModule, {});
  return <form action={action} className="space-y-4"><input type="hidden" name="id" value={module?.id ?? ""}/><label className="block text-sm font-bold">Titel<input className="field mt-1" name="title" defaultValue={module?.title} required maxLength={160}/></label><label className="block text-sm font-bold">Korte uitleg<textarea className="field mt-1 min-h-24" name="description" defaultValue={module?.description} maxLength={3000}/></label><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-bold">Periode<input className="field mt-1" name="period" defaultValue={module?.period} placeholder="Periode 1"/></label><label className="text-sm font-bold">Volgorde<input className="field mt-1" type="number" min="0" max="999" name="sortOrder" defaultValue={module?.sort_order ?? 0}/></label></div><label className="flex items-center gap-2 text-sm font-bold"><input className="size-4 accent-teal-700" type="checkbox" name="published" defaultChecked={module?.is_published}/>Zichtbaar voor studenten</label><fieldset><legend className="text-sm font-bold">Klassen</legend><div className="mt-2 grid gap-2 sm:grid-cols-2">{cohorts.map((c)=><label className="flex gap-2 text-sm" key={c.id}><input type="checkbox" className="size-4 accent-teal-700" name="cohortIds" value={c.id} defaultChecked={module?.cohortIds?.includes(c.id)}/>{c.name}</label>)}</div></fieldset><fieldset><legend className="text-sm font-bold">Opdrachten in deze volgorde</legend><div className="mt-2 max-h-56 space-y-2 overflow-y-auto rounded-xl border border-slate-200 p-3">{assignments.map((a)=><label className="flex gap-2 text-sm" key={a.id}><input type="checkbox" className="mt-0.5 size-4 accent-teal-700" name="assignmentIds" value={a.id} defaultChecked={module?.assignmentIds?.includes(a.id)}/>{a.title}</label>)}</div></fieldset><Message state={state}/><Button disabled={pending}>{pending ? "Opslaan…" : module ? "Module bijwerken" : "Module aanmaken"}</Button></form>;
}

export function FeedbackMomentForm({ moment, cohorts, modules, assignments }: { moment?: any; cohorts: Option[]; modules: Option[]; assignments: Option[] }) {
  const [state, action, pending] = useActionState(saveFeedbackMoment, {});
  return <form action={action} className="space-y-4"><input type="hidden" name="id" value={moment?.id ?? ""}/><label className="block text-sm font-bold">Titel<input className="field mt-1" name="title" required defaultValue={moment?.title}/></label><label className="block text-sm font-bold">Wat moeten studenten voorbereiden?<textarea className="field mt-1 min-h-24" name="instructions" defaultValue={moment?.instructions}/></label><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-bold">Soort<select className="field mt-1" name="kind" defaultValue={moment?.kind ?? "teacher_feedback"}><option value="quick_check">Snelle check</option><option value="peer_feedback">Feedback van medestudent</option><option value="teacher_feedback">Feedback van docent</option><option value="conversation">Voortgangsgesprek</option></select></label><label className="text-sm font-bold">Status<select className="field mt-1" name="status" defaultValue={moment?.status ?? "planned"}><option value="planned">Gepland</option><option value="open">Nu actief</option><option value="closed">Afgerond</option></select></label><label className="text-sm font-bold">Datum en tijd<input className="field mt-1" type="datetime-local" name="scheduledAt" required defaultValue={moment?.scheduled_at?.slice(0,16)}/></label><label className="text-sm font-bold">Klas<select className="field mt-1" name="cohortId" required defaultValue={moment?.cohort_id ?? ""}><option value="">Kies een klas</option>{cohorts.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="text-sm font-bold">Module<select className="field mt-1" name="moduleId" defaultValue={moment?.module_id ?? ""}><option value="">Geen module</option>{modules.map(m=><option key={m.id} value={m.id}>{m.title}</option>)}</select></label><label className="text-sm font-bold">Opdracht<select className="field mt-1" name="assignmentId" defaultValue={moment?.assignment_id ?? ""}><option value="">Geen opdracht</option>{assignments.map(a=><option key={a.id} value={a.id}>{a.title}</option>)}</select></label></div><Message state={state}/><Button disabled={pending}>{pending ? "Opslaan…" : moment ? "Moment bijwerken" : "Feedbackmoment plannen"}</Button></form>;
}

export function FeedbackTemplateForm() {
  const [state, action, pending] = useActionState(saveFeedbackTemplate, {});
  return <form action={action} className="space-y-3"><label className="block text-sm font-bold">Naam sjabloon<input className="field mt-1" name="title" required placeholder="Bijvoorbeeld: onderbouwing"/></label><label className="block text-sm font-bold">Wat gaat al goed?<textarea className="field mt-1 min-h-20" name="feedbackText" required/></label><label className="block text-sm font-bold">Volgende stap<textarea className="field mt-1 min-h-20" name="feedforwardText" required/></label><Message state={state}/><Button disabled={pending}>{pending ? "Opslaan…" : "Sjabloon bewaren"}</Button></form>;
}
